"""initial schema

Revision ID: fc73d4701487
Revises: 
Create Date: 2026-08-25 02:01:36.288825
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'fc73d4701487'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('agent_run_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('org_connection_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_use_id', sa.String(length=128), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('state', sa.Enum('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approvalstate'), nullable=False),
    sa.Column('change_hash', sa.String(length=64), nullable=False),
    sa.Column('state_fingerprint', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_reason', sa.Text(), nullable=True),
    sa.Column('approvals_required', sa.Integer(), nullable=False),
    sa.Column('eligible_roles', sa.JSON(), nullable=True),
    sa.Column('require_separate_approver', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('modified_arguments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index('ix_appr_tenant_state', ['organization_id', 'state'], unique=False)
        batch_op.create_index('ix_appr_user_state', ['user_id', 'state'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_change_hash'), ['change_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('org_connection_id', sa.String(length=64), nullable=True),
    sa.Column('sf_org_id', sa.String(length=32), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('agent_run_id', sa.String(length=64), nullable=True),
    sa.Column('tool_execution_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('salesforce_object', sa.String(length=128), nullable=True),
    sa.Column('record_ids', sa.JSON(), nullable=True),
    sa.Column('before_values', sa.JSON(), nullable=True),
    sa.Column('after_values', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=True),
    sa.Column('approval_state', sa.Enum('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approvalstate'), nullable=True),
    sa.Column('execution_state', sa.Enum('PLANNED', 'PROPOSED', 'APPROVED', 'EXECUTING', 'SUCCEEDED', 'PARTIALLY_SUCCEEDED', 'FAILED', 'SKIPPED', name='executionstate'), nullable=True),
    sa.Column('deployment_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_org_connection_id'), ['org_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_audit_tenant_created', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('change_sets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('org_connection_id', sa.String(length=64), nullable=False),
    sa.Column('agent_run_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'VALIDATING', 'VALIDATED', 'VALIDATION_FAILED', 'AWAITING_APPROVAL', 'APPROVED', 'DEPLOYING', 'DEPLOYED', 'DEPLOY_FAILED', 'ROLLED_BACK', name='changesetstate'), nullable=False),
    sa.Column('source_files', sa.JSON(), nullable=True),
    sa.Column('package_manifest', sa.JSON(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('test_level', sa.String(length=32), nullable=False),
    sa.Column('run_tests', sa.JSON(), nullable=True),
    sa.Column('validation_deploy_id', sa.String(length=64), nullable=True),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('deploy_id', sa.String(length=64), nullable=True),
    sa.Column('deploy_result', sa.JSON(), nullable=True),
    sa.Column('approval_id', sa.String(length=64), nullable=True),
    sa.Column('rollback_plan', sa.JSON(), nullable=True),
    sa.Column('rolled_back_deploy_id', sa.String(length=64), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_sets_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_sets_org_connection_id'), ['org_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_sets_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_sets_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_cs_tenant_created', ['organization_id', 'created_at'], unique=False)

    op.create_table('data_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('org_connection_id', sa.String(length=64), nullable=False),
    sa.Column('agent_run_id', sa.String(length=64), nullable=True),
    sa.Column('approval_id', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('sobject', sa.String(length=128), nullable=False),
    sa.Column('sf_job_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('records_total', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('failures_sample', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_jobs_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_jobs_org_connection_id'), ['org_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_jobs_sf_job_id'), ['sf_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_datajob_tenant', ['organization_id', 'created_at'], unique=False)

    op.create_table('deployments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('agent_run_id', sa.String(length=64), nullable=True),
    sa.Column('change_set_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('org_connection_id', sa.String(length=64), nullable=False),
    sa.Column('salesforce_deploy_id', sa.String(length=64), nullable=True),
    sa.Column('check_only', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('components_total', sa.Integer(), nullable=False),
    sa.Column('components_failed', sa.Integer(), nullable=False),
    sa.Column('tests_total', sa.Integer(), nullable=False),
    sa.Column('tests_failed', sa.Integer(), nullable=False),
    sa.Column('package_manifest', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_change_set_id'), ['change_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_org_connection_id'), ['org_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_salesforce_deploy_id'), ['salesforce_deploy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_user_id'), ['user_id'], unique=False)

    op.create_table('external_connections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('account', sa.String(length=200), nullable=False),
    sa.Column('credentials_enc', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'provider', 'account', name='uq_external_conn')
    )
    with op.batch_alter_table('external_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_connections_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_connections_provider'), ['provider'], unique=False)

    op.create_table('mcp_servers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('command', sa.String(length=512), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('secrets_enc', sa.Text(), nullable=True),
    sa.Column('env', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('tool_allowlist', sa.JSON(), nullable=True),
    sa.Column('risk_overrides', sa.JSON(), nullable=True),
    sa.Column('discovered_tools', sa.JSON(), nullable=True),
    sa.Column('last_discovery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_mcp_name')
    )
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_servers_organization_id'), ['organization_id'], unique=False)

    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('code_verifier', sa.String(length=256), nullable=False),
    sa.Column('login_url', sa.String(length=512), nullable=False),
    sa.Column('redirect_after', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_states_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_states_user_id'), ['user_id'], unique=False)

    op.create_table('org_knowledge',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('org_connection_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('OBJECT', 'FIELD', 'AUTOMATION', 'APEX', 'REPORT', 'PERMISSION', 'DEPLOYMENT', 'FAILURE', 'PATTERN', 'DIAGNOSIS', name='knowledgekind'), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_connection_id', 'kind', 'key', name='uq_knowledge')
    )
    with op.batch_alter_table('org_knowledge', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_lookup', ['org_connection_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_knowledge_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_knowledge_org_connection_id'), ['org_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_knowledge_organization_id'), ['organization_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('tool_executions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('agent_run_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('org_connection_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_use_id', sa.String(length=128), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('approval_state', sa.Enum('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approvalstate'), nullable=False),
    sa.Column('execution_state', sa.Enum('PLANNED', 'PROPOSED', 'APPROVED', 'EXECUTING', 'SUCCEEDED', 'PARTIALLY_SUCCEEDED', 'FAILED', 'SKIPPED', name='executionstate'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('salesforce_object', sa.String(length=128), nullable=True),
    sa.Column('record_ids', sa.JSON(), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_executions_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_tool_name'), ['tool_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_tool_run', ['agent_run_id', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('idp_kind', sa.Enum('LOCAL', 'OIDC', 'SAML', name='identityproviderkind'), nullable=False),
    sa.Column('idp_subject', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_idp_subject'), ['idp_subject'], unique=False)

    op.create_table('agent_policies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('allow_production_mutations', sa.Boolean(), nullable=False),
    sa.Column('approval_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('max_agent_steps', sa.Integer(), nullable=False),
    sa.Column('require_separate_approver', sa.Boolean(), nullable=False),
    sa.Column('approver_matrix', sa.JSON(), nullable=True),
    sa.Column('disabled_tools', sa.JSON(), nullable=True),
    sa.Column('max_bulk_records', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_policies_organization_id'), ['organization_id'], unique=True)

    op.create_table('approval_decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'RELEASE_MANAGER', 'SECURITY_ADMIN', 'DEVELOPER', 'ANALYST', 'VIEWER', name='role'), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_change_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_id', 'user_id', name='uq_approval_voter')
    )
    with op.batch_alter_table('approval_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_appr_dec_approval', ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_decisions_approval_id'), ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_decisions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_decisions_user_id'), ['user_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'RELEASE_MANAGER', 'SECURITY_ADMIN', 'DEVELOPER', 'ANALYST', 'VIEWER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('ix_membership_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('org_connections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('sf_org_id', sa.String(length=32), nullable=False),
    sa.Column('sf_user_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=False),
    sa.Column('instance_url', sa.String(length=512), nullable=False),
    sa.Column('login_url', sa.String(length=512), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('org_type', sa.String(length=64), nullable=False),
    sa.Column('api_version', sa.String(length=16), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_fingerprint', sa.String(length=32), nullable=False),
    sa.Column('scopes', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sf_org_id', name='uq_tenant_org')
    )
    with op.batch_alter_table('org_connections', schema=None) as batch_op:
        batch_op.create_index('ix_org_conn_tenant', ['organization_id'], unique=False)
        batch_op.create_index('ix_org_conn_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_connections_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_connections_sf_org_id'), ['sf_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_connections_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('org_connection_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_connection_id'], ['org_connections.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conv_tenant_created', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index('ix_conv_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_org_connection_id'), ['org_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('org_connection_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.Enum('IDLE', 'UNDERSTANDING', 'INSPECTING', 'PLANNING', 'AWAITING_APPROVAL', 'EXECUTING', 'VALIDATING', 'VERIFYING', 'COMPLETED', 'FAILED', name='agentstate'), nullable=False),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('steps_used', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=True),
    sa.Column('pending_tool_results', sa.JSON(), nullable=True),
    sa.Column('pending_approval_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_org_connection_id'), ['org_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_run_conv', ['conversation_id', 'created_at'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('agent_run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_msg_conv_created', ['conversation_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_msg_conv_created')
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_messages_agent_run_id'))

    op.drop_table('messages')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_run_conv')
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_org_connection_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_conversation_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_org_connection_id'))
        batch_op.drop_index('ix_conv_user_created')
        batch_op.drop_index('ix_conv_tenant_created')

    op.drop_table('conversations')
    with op.batch_alter_table('org_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_org_connections_sf_org_id'))
        batch_op.drop_index(batch_op.f('ix_org_connections_organization_id'))
        batch_op.drop_index('ix_org_conn_user')
        batch_op.drop_index('ix_org_conn_tenant')

    op.drop_table('org_connections')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_external_id'))
        batch_op.drop_index('ix_membership_user')

    op.drop_table('memberships')
    with op.batch_alter_table('approval_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_approval_decisions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_approval_decisions_approval_id'))
        batch_op.drop_index('ix_appr_dec_approval')

    op.drop_table('approval_decisions')
    with op.batch_alter_table('agent_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_policies_organization_id'))

    op.drop_table('agent_policies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_idp_subject'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_tool_run')
        batch_op.drop_index(batch_op.f('ix_tool_executions_user_id'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_agent_run_id'))

    op.drop_table('tool_executions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    with op.batch_alter_table('org_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_knowledge_organization_id'))
        batch_op.drop_index(batch_op.f('ix_org_knowledge_org_connection_id'))
        batch_op.drop_index(batch_op.f('ix_org_knowledge_key'))
        batch_op.drop_index('ix_knowledge_lookup')

    op.drop_table('org_knowledge')
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_states_organization_id'))

    op.drop_table('oauth_states')
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_servers_organization_id'))

    op.drop_table('mcp_servers')
    with op.batch_alter_table('external_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_connections_provider'))
        batch_op.drop_index(batch_op.f('ix_external_connections_organization_id'))

    op.drop_table('external_connections')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_user_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_salesforce_deploy_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_org_connection_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_change_set_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_agent_run_id'))

    op.drop_table('deployments')
    with op.batch_alter_table('data_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_datajob_tenant')
        batch_op.drop_index(batch_op.f('ix_data_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_data_jobs_sf_job_id'))
        batch_op.drop_index(batch_op.f('ix_data_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_data_jobs_org_connection_id'))
        batch_op.drop_index(batch_op.f('ix_data_jobs_agent_run_id'))

    op.drop_table('data_jobs')
    with op.batch_alter_table('change_sets', schema=None) as batch_op:
        batch_op.drop_index('ix_cs_tenant_created')
        batch_op.drop_index(batch_op.f('ix_change_sets_user_id'))
        batch_op.drop_index(batch_op.f('ix_change_sets_organization_id'))
        batch_op.drop_index(batch_op.f('ix_change_sets_org_connection_id'))
        batch_op.drop_index(batch_op.f('ix_change_sets_agent_run_id'))

    op.drop_table('change_sets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_created')
        batch_op.drop_index('ix_audit_tenant_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_org_connection_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_agent_run_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_user_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_organization_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_change_hash'))
        batch_op.drop_index(batch_op.f('ix_approvals_agent_run_id'))
        batch_op.drop_index('ix_appr_user_state')
        batch_op.drop_index('ix_appr_tenant_state')

    op.drop_table('approvals')
    # ### end Alembic commands ###
