"""Customer-owned Salesforce External Client Apps

Revision ID: 2009338574a8
Revises: a6c82321693f
Create Date: 2026-08-26 02:59:18.875726
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2009338574a8'
down_revision: str | None = 'a6c82321693f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesforce_apps',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('client_id', sa.String(length=512), nullable=False),
    sa.Column('client_secret_ref', sa.Text(), nullable=True),
    sa.Column('login_url', sa.String(length=512), nullable=False),
    sa.Column('api_version', sa.String(length=16), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_sfapp_company_name')
    )
    op.create_index(op.f('ix_salesforce_apps_company_id'), 'salesforce_apps', ['company_id'], unique=False)
    op.create_index(op.f('ix_salesforce_apps_project_id'), 'salesforce_apps', ['project_id'], unique=False)
    op.create_index('ix_sfapp_company', 'salesforce_apps', ['company_id'], unique=False)
    op.add_column('oauth_states', sa.Column('salesforce_app_id', sa.String(length=64), nullable=True))
    op.add_column('salesforce_connections', sa.Column('salesforce_app_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salesforce_connections', 'salesforce_app_id')
    op.drop_column('oauth_states', 'salesforce_app_id')
    op.drop_index('ix_sfapp_company', table_name='salesforce_apps')
    op.drop_index(op.f('ix_salesforce_apps_project_id'), table_name='salesforce_apps')
    op.drop_index(op.f('ix_salesforce_apps_company_id'), table_name='salesforce_apps')
    op.drop_table('salesforce_apps')
    # ### end Alembic commands ###
