"""Company-level production clearance

Revision ID: 9f725d563a52
Revises: 2009338574a8
Create Date: 2026-08-26 03:48:23.239099
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9f725d563a52'
down_revision: str | None = '2009338574a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `server_default` is not decoration. Autogenerate produced this column as
    # NOT NULL with no default, which works on an empty database and fails on
    # every real one: existing rows get NULL and Postgres refuses the
    # constraint. Verified by inserting a company and then upgrading.
    #
    # `false` is also the only safe value to backfill. A company that existed
    # before this column did was never asked whether it wanted the agent
    # touching production, and inferring consent from silence is exactly the
    # wrong default for the setting whose blast radius is a live Salesforce org.
    op.add_column(
        'companies',
        sa.Column(
            'allow_production_mutations',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'allow_production_mutations')
    # ### end Alembic commands ###
