"""Enterprise identity: session revocation and IdP-granted membership tracking

Two columns, both in service of de-provisioning actually working.

`users.session_version` — a session token carries the version it was minted at.

Bumping this column invalidates every token ever issued to that user, in every
browser, on their next request — which is what makes "sign out everywhere" and
"revoke access now" facts rather than promises about cookie expiry.

`project_memberships.external_id` — the identity provider's subject, when an
IdP granted the membership. Its presence is what lets an SSO login revoke what
the directory no longer asserts while leaving hand-granted memberships alone.
Without it, one SSO login would silently revoke every contractor a project
admin had added by invitation.

Note the `server_default`. Alembic autogenerated this column as NOT NULL with
no default, which would fail on any table that already has rows — every real
deployment. Existing users start at version 1, which is also what a token with
no `sv` claim is treated as, so upgrading does not sign anybody out.

Revision ID: a6c82321693f
Revises: 4f03de264731
Create Date: 2026-08-25 18:41:55.297849
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a6c82321693f"
down_revision: str | None = "4f03de264731"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "session_version",
                sa.Integer(),
                nullable=False,
                server_default="1",
            )
        )

    with op.batch_alter_table("project_memberships", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("external_id", sa.String(length=200), nullable=True)
        )
        batch_op.create_index(
            "ix_project_memberships_external_id", ["external_id"], unique=False
        )


def downgrade() -> None:
    with op.batch_alter_table("project_memberships", schema=None) as batch_op:
        batch_op.drop_index("ix_project_memberships_external_id")
        batch_op.drop_column("external_id")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("session_version")
